// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LvtD-50QJquyu3_NZ7ARBChbJO5uMXc',
    appId: '1:362008093276:web:06167dfaa3abb5d8effc99',
    messagingSenderId: '362008093276',
    projectId: 'mov3-f',
    authDomain: 'mov3-f.firebaseapp.com',
    storageBucket: 'mov3-f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgr36ZP0-E-nQC4OtNsSVUgAtEsCaoQQ',
    appId: '1:362008093276:android:b4ab84b4bd2da8a5effc99',
    messagingSenderId: '362008093276',
    projectId: 'mov3-f',
    storageBucket: 'mov3-f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_LvtD-50QJquyu3_NZ7ARBChbJO5uMXc',
    appId: '1:362008093276:web:1aa718ac736ee014effc99',
    messagingSenderId: '362008093276',
    projectId: 'mov3-f',
    authDomain: 'mov3-f.firebaseapp.com',
    storageBucket: 'mov3-f.firebasestorage.app',
  );

}